### ISSUE TITLE
TraceId defined as 64bit integer

### ISSUE THREAD

**Issue by aliostad** [openzipkin-attic/zipkin-csharp#35]
I can see that TraceId has been defined as 64bit integer [here](https://github.com/openzipkin/zipkin-csharp/blob/724ce0ebc63f851daca76b8cc7b65ed12e1cbeb8/src/Zipkin.Core/TraceHeader.cs#L40).

The problem is spec defines TraceId as 64bit or 128bit and I personally am using 128bit at work. So I guess we need to fix it.

So @adriancole how is this done in Java? I do not believe there is a 128bit integer in Java (except UUID), so has it been defined as some kind of union type or defined as long?

### PS.

There is an option in C# to create implicit conversions and I think this is probably the best approach.

**Comment by codefromthecrypt** [comment]
there's no fixed length 128 bit type in java (64bit integer was only used
for its width, not because numeric is helpful)

for portability, we added traceIdHigh in java (and thrift) which has a
benefit of showing how to step-down into 64bit and also being fixed-width
:) In json it is still represented as a single hex string and in thrift,
there is a field for traceIdHigh
https://github.com/openzipkin/zipkin/blob/master/zipkin/src/main/java/zipkin/Span.java#L66
 https://github.com/openzipkin/zipkin-api

**Comment by aliostad** [comment]
Thank you. I will look into this and have a feeling a type with implicit conversions probably is the solution.

**Comment by aliostad** [comment]
Discussed that the 128bit is in a sticky situation and best not implemented, (IMHO).

**Comment by codefromthecrypt** [comment]
When this is picked up, it would be most straight forward to do what others
are doing and add another 64bit field called traceIdHigh which is also
defined in the the thrift struct

**Comment by codefromthecrypt** [comment]
> Discussed that the 128bit is in a sticky situation and best not implemented


Note: "best not implemented" is your personal opinion, and in no way
represents status quo in zipkin. I suspect other csharp libraries will
support 128 bit ids similar to others in zipkin

**Comment by aliostad** [comment]
Hi @adriancole as I said, using a UUID was the most natural way to implement this, not to use two int64. At the end of the day, since the spec is not prescriptive in terms of encoding this, I find it more harmful rather than helpful.

I have been involved in terms of review or contribution to specs since year 2000 when the specifications of XML and SOAP were being ratified. I must say this part of standard is not its strongest point.

**Comment by codefromthecrypt** [comment]
Ali are you suggesting you singularly have more experience and zipkin than
everyone that were involved in this decision? Your tone seems a bit off for
someone running a community project.

**Comment by codefromthecrypt** [comment]
Here is the issue you can more effectively argue with if that is your goal.
I'm looking forward to a time where you can put other users in front and
consider why maybe a decision will be better for other people than you
personally. This will make you even better choice to lead a library for
others. If you arent really interested in what existing users need besides
yourself possibly just working on your own is best.


https://github.com/openzipkin/zipkin/issues/1262
