### ISSUE TITLE
Move this repository to https://github.com/openzipkin-attic or aliostad's account

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin-attic/zipkin-csharp#36]
## Summary

zipkin-csharp moved to the OpenZipkin org Sep 2016 after formerly being a single-person project. Unfortunately, there has been little progress in the 10 months since. @aliostad is the most successful user/maintainer. Others have been less successful. The code hasn't progressed notably, and it is missing major features and example projects present in other tracers in the org. The combination of these factors make it a poor choice to advertise and a support liability for others.

### Overall plan
* Either move the repo to https://github.com/openzipkin-attic, or transfer ownership into @aliostad's account.
  * If the latter, @aliostad will need to delete his fork so that we can move it
* Regardless of above choice, perform no further releases under the openzipkin account.
  * There has only been one release to nuget: Zipkin.Core 0.1.0-beta
* To the degree other users besides ones implicitly cc'd here exist, they can be notified.
  * In the last 6 weeks, there have only been 38 downloads of the package, so collateral damage is minimal.
  * https://github.com/openzipkin/zipkin/issues/1518 will lay out the alternative answer

### Background
At the time zipkin-csharp was added, this was under different circumstances. I think I was too hasty bringing it in, particularly as it was abandoned code. The project hasn't become healthy since. Since being in OpenZipkin, @aliostad setup nuget and performed some maintenance work on file names and structure. One pull request by @IlyaRaichman, to add a constructor, was accepted. Unfortunately, others have been less successful: Pull requests by @alexvaluyskiy @ismaelhamed continue to sit (for months) and @ernado-x's work was closed (even if for good reason). No one is working the issues backlog. For example issues by @rogeralsing last september have not been addressed. No work has been done to progress the project towards model changes or features made in the last year. Meanwhile, the amount of users asking about csharp increases.

### Impact of canceling this work
Unfortunately, status quo has not worked, and keeping this repository here despite that is not an option. This means at least a package namespace change if the work continues.

If this project continues under @aliostad's account, besides being published under a different nuget account there will likely be no change. In any case, any user who wants to continue this work can. Those who have unmerged PRs probably already are working on their own builds.

Due to the low activity here and also the low download count (38 in six weeks including whatever activity made by the current maintainer), collateral damage should be minimal. However, it will hurt some, and feel free to voice your complaints if nothing else to let us feel them.

On the other hand a fully supported tracer is something we'd expect to grow the OpenZipkin ecosystem. Please look at https://github.com/openzipkin/zipkin/issues/1518 and ask for features on the next option.

**Comment by basvanbeek** [comment]
I'm personally in favor of moving this project to openzipkin-attic as to make sure we as openzipkin are clear about this project being kept available in its current form but without our maintenance and support guarantees. It is too soon to hand over the project entirely to a third party. If a third party wants to keep this alive they can work on their fork and hopefully gain critical mass but we shouldn't just hand over the project and throw are hands in the air regarding future availability; maintained or not.

**Comment by abesto** [comment]
Closing, since the repo is now in openzipkin-attic. Feel free to reopen if that's the wrong move.
